# Generated by Django 4.2.4 on 2023-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(default='{{% post.titulo %}}', max_length=255),
        ),
    ]
